### ISSUE TITLE
Add Feature: Send files from messeger to remote terminal

### ISSUE THREAD

**Issue by sahasd** [avikj/fbash#2]
Add functionality to fbash so you can drag file into messenger, then type command to save that file on the remote client where it is being run.

**Comment by avikj** [comment]
Good idea. I will try to add this functionality in the near future.

**Comment by avikj** [comment]
This functionality has been added in v1.4.0, as the `savefile` command. Check it out on the docs [here](https://github.com/avikj/fbash/blob/master/DOCS.md#savefile).
